name: GitHub_Action_CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  API_TOKEN: ${{ secrets.API_KEY }}
  NEWS_TOKEN: ${{ secrets.NEWS_API_KEY }}
  FB_MESSAGING_TOKEN: ${{ secrets.FB_MESSAGING_KEY }}
  FIREBASE_SERVICES: ${{ secrets.FIREBASE_SECRET }}
  FIREBASE_PUSH_FCM: ${{ secrets.FIREBASE_PUSH_FCM }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17

      - name: Load API Token from secrets
        run: |
          chmod +x .github/workflows/setup_env.sh
          .github/workflows/setup_env.sh

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Lint
        run: |
          chmod +x ./gradlew
          ./gradlew lintDebug

      - name: Build
        run: ./gradlew assembleRelease

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Load API Token from secrets
        run: |
          chmod +x .github/workflows/setup_env.sh
          .github/workflows/setup_env.sh

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}


      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17

      - name: Run Test
        run: ./gradlew testDebug --stacktrace

  instrumental-test:
    runs-on: macos-latest
    needs: test

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Load API Token from secrets
        run: |
          chmod +x .github/workflows/setup_env.sh
          .github/workflows/setup_env.sh

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}


      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace